In [1]:


import numpy as np
import pandas as pd


df = pd.read_csv('./train.csv')

df_num = df.select_dtypes(include = ['float64', 'int64'])
df_num = df_num.dropna()
x_train = df_num.iloc[:,1:-1]
y_train = df_num['SalePrice']
X_features = x_train.columns
x_train = np.array(x_train)
y_train = np.array(y_train)
print(x_train)
print(y_train)

def zscore_normalize_features(X):
    mu = np.mean(X, axis=0)                
    sigma = np.std(X, axis=0)                  
    X_norm = (X - mu) / sigma      

    return (X_norm, mu, sigma)

X_norm_train, X_mu, X_sigma = zscore_normalize_features(x_train)

print(X_mu)
print(X_sigma)

[[6.000e+01 6.500e+01 8.450e+03 ... 0.000e+00 2.000e+00 2.008e+03]
 [2.000e+01 8.000e+01 9.600e+03 ... 0.000e+00 5.000e+00 2.007e+03]
 [6.000e+01 6.800e+01 1.125e+04 ... 0.000e+00 9.000e+00 2.008e+03]
 ...
 [7.000e+01 6.600e+01 9.042e+03 ... 2.500e+03 5.000e+00 2.010e+03]
 [2.000e+01 6.800e+01 9.717e+03 ... 0.000e+00 4.000e+00 2.010e+03]
 [2.000e+01 7.500e+01 9.937e+03 ... 0.000e+00 6.000e+00 2.008e+03]]
[208500 181500 223500 ... 266500 142125 147500]
[5.61462979e+01 7.06654773e+01 1.01229563e+04 6.21231044e+00
 5.56110616e+00 1.97226494e+03 1.98568332e+03 1.08487957e+02
 4.38399643e+02 4.45896521e+01 5.94125781e+02 1.07711508e+03
 1.17358430e+03 3.53258698e+02 4.56824264e+00 1.53141124e+03
 4.13916146e-01 5.53077609e-02 1.58073149e+00 3.81801963e-01
 2.86440678e+00 1.04281891e+00 6.57627119e+00 6.03925067e-01
 1.97839964e+03 1.87867975e+00 5.02955397e+02 9.26101695e+01
 4.61302409e+01 2.18447814e+01 3.34879572e+00 1.61008029e+01
 2.93487957e+00 2.34290812e+01 6.33987511e+00 2.00779572

In [ ]:

import numpy as np
import pandas as pd

#Question 1



df=pd.read_csv('./test.csv')

df_num = df.select_dtypes(include = ['float64', 'int64']) #selecting numeric columns, (data type float or integer)
df_num = df_num.dropna() #removing missing values


x_test = df_num.iloc[:,1:] #selects all rows, but excludes the first column (at index 0). This is because the first column does not provide useful information for our regression analysis, as it is only an identifier column.
x_test = np.array(x_test) #converts dataframe into a numpy array
print(x_test)
def zscore_normalize_features(X): #performs z-score normalisation, so our features will be transformed to have a mean of 0 and standard deviation 1. This normalisation is particularly useful if different features have different units. If one features tends to have values of much larger magnitude, it will dominate the training process, so z-score normalisation helps prevent that.
                     
    X_norm = (X - X_mu) / X_sigma      

    return (X_norm, X_mu, X_sigma)


X_norm_test, X_mu, X_sigma = zscore_normalize_features(x_test)


w_final=np.array([-8011.41949503, -2554.88144257,  4371.01684486, 25300.23441283,
  4971.24485624,  7414.6478549,   3530.17191891,  6203.30658114,
  4930.42056713,   138.71580287, -1017.24755316,  4203.24404008,
  7060.34994443,  8485.56937076,   249.84729751, 12331.62047256,
  4557.03199214,   566.25084138,  4001.4751966,    264.02161654,
 -7473.23854297, -4736.50310288,  8860.92989084,  3198.91077193,
  -412.32382937,  9937.32513012,  2198.63407278,  2656.09106672,
  -277.77367228,   265.29134584,  1002.93366631,  3310.6169966,
 -2516.37594624,  -682.08787893,  -527.42969216,  -384.33861248])  #weight matrix


b_final=185497.75 #final bias


m,_ = X_norm_test.shape
for i in range (m):
  predictions=np.dot(X_norm_test[i],w_final) +b_final   #predicted values from applying our model to our normalised testing set.
print(predictions)







[[2.0000e+01 8.0000e+01 1.1622e+04 ... 0.0000e+00 6.0000e+00 2.0100e+03]
 [2.0000e+01 8.1000e+01 1.4267e+04 ... 1.2500e+04 6.0000e+00 2.0100e+03]
 [6.0000e+01 7.4000e+01 1.3830e+04 ... 0.0000e+00 3.0000e+00 2.0100e+03]
 ...
 [1.6000e+02 2.1000e+01 1.8940e+03 ... 0.0000e+00 4.0000e+00 2.0060e+03]
 [2.0000e+01 1.6000e+02 2.0000e+04 ... 0.0000e+00 9.0000e+00 2.0060e+03]
 [6.0000e+01 7.4000e+01 9.6270e+03 ... 0.0000e+00 1.1000e+01 2.0060e+03]]
259679.63656322556


In [ ]:
#Question 2


import statsmodels.api as sm



#Add a constant to X_train for the intercept



X_b_train = sm.add_constant(X_norm_train) #adds a column of 1s, representing the intercept in the regression model. This is because OLS (Ordinary Least Squares) requires an intercept term to estimate the relationship between variables. We can account for bias by including this intercept term.

# Fit the OLS model
ols_model = sm.OLS(y_train, X_b_train).fit() #Fits an OLS model with X_b_train as input features and y_train as target values.

# Print the summary of the regression
print(ols_model.summary()) #prints regression statistics such as R Squared (gives us an idea of how well the features explain variability in the target, for example R^2 = 0.85 means that 85% of the variance in y can be explained by our inputs). p-values, Coefficients, Standard Errors, F-Statistic.

X_b_test = sm.add_constant(X_norm_test) #we need to add a column of ones to the testing set aswell, otherwise we will get less accurate predictions. In fact, the constant added will be the same as that of the training set.
predictions_test = ols_model.predict(X_b_test)

[[ 1.          0.09229529 -0.23357027 ... -0.14140664 -1.61534509
   0.15308355]
 [ 1.         -0.86569565  0.38483378 ... -0.14140664 -0.49871497
  -0.59629052]
 [ 1.          0.09229529 -0.10988946 ... -0.14140664  0.99012519
   0.15308355]
 ...
 [ 1.          0.33179303 -0.19234334 ... 14.94738799 -0.49871497
   1.65183171]
 [ 1.         -0.86569565 -0.10988946 ... -0.14140664 -0.87092501
   1.65183171]
 [ 1.         -0.86569565  0.17869909 ... -0.14140664 -0.12650493
   0.15308355]]
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.810
Model:                            OLS   Adj. R-squared:                  0.804
Method:                 Least Squares   F-statistic:                     135.7
Date:                Wed, 05 Feb 2025   Prob (F-statistic):               0.00
Time:                        16:56:43   Log-Likelihood:                -13358.
No. Observations:                1