In [ ]:
import numpy as np
import random


#Question 1

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]


layer_outputs1 = np.dot(inputs, np.array(weights).T) + biases
print(layer_outputs1)         
weights2 = np.random.rand(len(weights), len(weights[0]))
print(weights2)

layer_outputs2= np.dot(inputs, np.array(weights2).T) + biases

#We flatten the weights and inputs to a 1 dimensional array, so we can aggregate to one output.
weights2_flat = weights2.flatten()  # Flatten weights to a single 1D array
inputs_flat = np.array(inputs).flatten()  # Flatten inputs to a single 1D array
combined_bias = np.sum(biases)
single_output = np.dot(inputs_flat, weights2_flat) + combined_bias
print("Single Output:", single_output)

#Question 2


def relu(x):
    return np.maximum(0,x)

relu(layer_outputs1)
relu(layer_outputs2)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[0.33905979 0.25084926 0.43632908 0.92057604]
 [0.29246464 0.40200298 0.42416697 0.32787065]
 [0.3300373  0.72324688 0.59726866 0.32601114]]
